# Generated by Django 5.1.7 on 2025-03-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0003_articletag_articlepage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='intro',
            field=models.CharField(max_length=80),
        ),
    ]
