# Generated by Django 5.1.7 on 2025-03-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_blog', '0004_alter_articlepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='caption',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
